name: rclone

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: rclone-install
        run: |
          # 安装 rclone
          curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip
          unzip rclone-current-linux-amd64.zip
          cd rclone-*-linux-amd64
          sudo mv rclone /usr/bin
          sudo chmod +x /usr/bin/rclone
      - name: rclone-config
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
        run: |
          # 写配置文件
          mkdir -p ~/.config/rclone/
          cat << EOF > ~/.config/rclone/rclone.conf
          $RCLONE_CONFIG
          EOF
      - name: install-BBDown
        run: |
          wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          rm packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          sudo apt-get install -y apt-transport-https
          sudo apt-get install -y dotnet-sdk-6.0
          dotnet tool install --global BBDown
      - name: BBDown run
        run: |
          sudo mkdir -p /home/runner/dd
          sudo bash test.sh
      - name: rclone-run
        run: |
          # Rclone-Mount
          sudo apt-get update && sudo apt-get install -y fuse
          #sudo rclone mount dd:/ $HOME/dd --copy-links --allow-other --allow-non-empty --umask 000 --daemon
          sudo rclone move -V /home/runner/dd dd:/河野华
